pipeline {
    agent any
    stages {
        stage('Test') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }

            steps {
                sh 'node --version'
            }
        }
    }
}