pipeline {
    agent none

    environment { 
        SERVER_TO_DEPLOY = 'mramiro.com.br'
    }

    stages {
        stage('Build') {
            agent {
                docker { image 'node:20-alpine' }
            }
            steps {
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                sh 'uname -a'
                sh 'node --version'
                sh 'npm --version'
                sh 'npm ci'
                sh 'ls -la'
            }
        }
    }
}