pipeline {
    agent any
    stages {
        stage('Test') {
            agent {
                sh '''
                docker -v
                docker info
                '''
            }

            steps {
                sh 'node --version'
            }
        }
    }
}